### ISSUE TITLE
Bot doesnt respond to messages

### ISSUE THREAD

**Issue by mishailovic** [thehamkercat/Telegram_VC_Bot#1]
I followed the installation instructions. Launched the bot. The terminal displays the message "Bot started" but the bot does not respond to messages. What should I do?

**Comment by thehamkercat** [comment]
1. check if the `SUDO_CHAT_ID` in `config.py` is correct or not.
2. bot should have admins permission in chat
3. you can't access bot in pm

**Comment by mishailovic** [comment]
Didn't know that the bot needs administrator rights. Thanks for your help. I think it would be nice to add this to the readme.

**Comment by thehamkercat** [comment]
Will add
