### ISSUE TITLE
Add heroku support please

### ISSUE THREAD

**Issue by ShinchanNohara001** [thehamkercat/Telegram_VC_Bot#2]

**Comment by thehamkercat** [comment]
currently heroku support is not possible because the free dyno has only 512MB ram which is too low for telegram to run, we have to wait for pytgcalls to be released before we can integrate that into this project, and it will take a month maybe. thanks for the support.

**Comment by Guru-25** [comment]
PyTgCalls came

**Comment by thehamkercat** [comment]
> PyTgCalls came

so? lol, heroku is supported obviously, but it's not stable for now. You can try it if you want.
