### ISSUE TITLE
Unable to run pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by Ng-hacker** [thehamkercat/Telegram_VC_Bot#21]
When i tried to run `pip3 install -r requirements.txt`, it was showing me the following error (in short):
ERROR: Could not find a version that satisfies the requirement OpenCC
ERROR: No matching distribution found for OpenCC

![image](https://user-images.githubusercontent.com/79059943/109529263-91f34d80-7adb-11eb-928a-f336c83e0834.png)

Kindly help me to resolve this issue on git bash...

**Comment by thehamkercat** [comment]
Try updating your python version and use linux ffs
