### ISSUE TITLE
Need a Dockerfile or Procfile

### ISSUE THREAD

**Issue by charindithjaindu** [thehamkercat/Telegram_VC_Bot#23]
can you please add the docker support or Heroku support

**Comment by thehamkercat** [comment]
OK, will add it today.

**Comment by SkyaTura** [comment]
I'm working on add a Dockerfile to this project, if that is Ok.

**Comment by thehamkercat** [comment]
> I'm working on add a Dockerfile to this project, if that is Ok.

It's ok

**Comment by thehamkercat** [comment]
Done
