### ISSUE TITLE
Need Heroku Support

### ISSUE THREAD

**Issue by Itz-fork** [thehamkercat/Telegram_VC_Bot#24]
Can  you please add **Heroku Support** for this!

**Comment by thehamkercat** [comment]
Yes, today

**Comment by Hirusha-H** [comment]
> Yes, today

huh?

**Comment by MotiPaak** [comment]
> Yes, today

Thanks, I'm waiting... 😙

**Comment by thehamkercat** [comment]
@Devanagaraj do it beech

**Comment by Hirusha-H** [comment]
> > Yes, today
> 
> Thanks, I'm waiting...

same here bruh!

**Comment by Devanagaraj** [comment]
> @Devanagaraj do it beech

NONOOOOOOOOOOOOOOOOOOO.... Let's Make noob pruf and heroku pruf

**Comment by thehamkercat** [comment]
> > @Devanagaraj do it beech
> 
> NONOOOOOOOOOOOOOOOOOOO.... Let's Make noob pruf and heroku pruf

wtf

**Comment by thehamkercat** [comment]
Done
