### ISSUE TITLE
tgcalls is not installing on reqs

### ISSUE THREAD

**Issue by charindithjaindu** [thehamkercat/Telegram_VC_Bot#29]
![image](https://user-images.githubusercontent.com/75799963/111939366-1856ea00-8af2-11eb-8fdd-83ae64fba08a.png)

**Comment by thehamkercat** [comment]
`pip3 install -U pip && pip3 install -U -r requirements.txt` 

it's already explained in README, try reading next time

**Comment by charindithjaindu** [comment]
Oh sorry sir,
anyway it worked
thank you sir
