### ISSUE TITLE
ERROR: Cannot install -r requirements.txt (line 2) because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by rktiwari00** [thehamkercat/Telegram_VC_Bot#51]
The conflict is caused by:
    pytgcalls 0.0.19 depends on tgcalls==0.0.12
    pytgcalls 0.0.18 depends on tgcalls==0.0.12
    pytgcalls 0.0.17 depends on tgcalls==0.0.11
    pytgcalls 0.0.16 depends on tgcalls==0.0.10
    pytgcalls 0.0.15 depends on tgcalls==0.0.10
    pytgcalls 0.0.14 depends on tgcalls==0.0.10
    pytgcalls 0.0.13 depends on tgcalls==0.0.9
    pytgcalls 0.0.12 depends on tgcalls==0.0.8
    pytgcalls 0.0.11 depends on tgcalls==0.0.7
    pytgcalls 0.0.10 depends on tgcalls==0.0.6
    pytgcalls 0.0.9 depends on tgcalls==0.0.5
    pytgcalls 0.0.8 depends on tgcalls==0.0.4
    pytgcalls 0.0.7 depends on tgcalls==0.0.4
    pytgcalls 0.0.6 depends on tgcalls==0.0.4
    pytgcalls 0.0.5 depends on tgcalls==0.0.3
    pytgcalls 0.0.4 depends on tgcalls==0.0.3
    pytgcalls 0.0.3 depends on tgcalls==0.0.3
    pytgcalls 0.0.2 depends on tgcalls==0.0.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
![Screenshot (3)](https://user-images.githubusercontent.com/23394879/116806808-0d5d9380-ab4d-11eb-9f96-b09e41186fd2.png)

**Comment by thehamkercat** [comment]
update your pip, it will fix that

**Comment by Tejas61900** [comment]
> update your pip, it will fix that

Accha , on windows

**Comment by thehamkercat** [comment]
> > update your pip, it will fix that
> 
> Accha , on windows

winhoes isn't supported, you know that very well

**Comment by Tejas61900** [comment]
> > > update your pip, it will fix that
> > 
> > 
> > Accha , on windows
> 
> winhoes isn't supported, you know that very well

So why u bully poor peeps 🥲

**Comment by thehamkercat** [comment]
> > > > update your pip, it will fix that
> > > 
> > > 
> > > Accha , on windows
> > 
> > 
> > winhoes isn't supported, you know that very well
> 
> So why u bully poor peeps 🥲
F
