### ISSUE TITLE
Bot isn't working

### ISSUE THREAD

**Issue by rktiwari00** [thehamkercat/Telegram_VC_Bot#52]
On checking log in heroku I found this error

heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=bhojpuri-chat.herokuapp.com request_id=a118f8fd-ffb7-415b-8c01-5ad7887ac461 fwd="47.29.123.63" dyno= connect= service= status=503 bytes= protocol=https

**Comment by thehamkercat** [comment]
sadly, heroku isn't supported, i just gave the deploy button, i won't solve issues related to that
