### ISSUE TITLE
Not working sometimes

### ISSUE THREAD

**Issue by mojtabaasg** [TheHamkerCat/Telegram_VC_Bot#68]
Sometimes I have to rerun it many times or using /leavevc and /joinvc several times to make it work.
whenever the bot is in voicechat and doesn't singing, it will leave the voicechat automatically after 10-120s.

**Comment by TheHamkerCat** [comment]
It's a bug of pytgcalls, so we can't really do anything, send the logs in [tgvcsupport](https://t.me/tgvcsupport)
