### ISSUE TITLE
Can't deploy in heroku "We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy"

### ISSUE THREAD

**Issue by Nisarga-Developer** [TheHamkerCat/Telegram_VC_Bot#72]
I was trying to deploy in heroku but I got error "We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy"

**Comment by TheHamkerCat** [comment]
Stop using heroku then, they're known for this shit
